### ISSUE TITLE
Support for newer Buds versions?

### ISSUE THREAD

**Issue by githubcatw** [ThePBone/GalaxyBudsFirmwareDownloader#1]
Is it possible to support newer Buds versions (Live, Pro)? Looks like they changed the server or XML name structure. I looked around in the plugin but couldn't find a URL.

**Comment by githubcatw** [comment]
...and guess what's a readme

**Comment by timschneeb** [comment]
The Buds Live and Buds Pro app use a modified OMA-DM protocol for firmware updates. It is absolutely painful to reverse it, but it is doable if you invest enough time.

Maybe I'll look into it, but for now, I'm intercepting the HTTPS traffic on my Android to retrieve firmware download links for the Buds Pro (with a proper OAuth authorization header and content generated by the app).

If you are looking for the Buds Pro firmware, I'm hosting a custom firmware provider API on my server: <https://fw.timschneeberger.me/firmware/download/R190XXU0AUC3>

(JSON API listing of my full backup: https://fw.timschneeberger.me/firmware)
